# Generated by Django 5.0.2 on 2024-03-08 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edblog', '0007_school_subject_set_student_enrolment_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edblog.set'),
        ),
    ]
