# Generated by Django 5.0.2 on 2024-03-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edblog', '0008_post_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sets',
            field=models.ManyToManyField(through='edblog.Enrolment', to='edblog.set'),
        ),
    ]
